=== Dani762/Boletin2/listahoteles.dtd
<!ELEMENT hoteles (agenda*,resenas*,habitaciones*)>
<!ELEMENT agenda (nombre*,telefono*,direccion*,ciudad,pais)>
<!ELEMENT resenas (estrellas*,descripcion*)>
<!ELEMENT habitaciones (individuales*,dobles*,triples*,suites*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle*,numero*)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT estrellas (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT individuales (#PCDATA)>
<!ELEMENT dobles (#PCDATA)>
<!ELEMENT triples (#PCDATA)>
<!ELEMENT suites (#PCDATA)>




<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>

=== Dani762/Boletin2/hoteles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hoteles SYSTEM "listahoteles.dtd">

<hoteles>
    <agenda>
       <nombre>
        Hotel Los Palacios
       </nombre>
       <telefono>
        677777777
       </telefono>
       <direccion>
            <calle>
                Avenida Realista
            </calle>
            <numero>
                35
            </numero>
       </direccion>
       <ciudad>
        Zaragoza
       </ciudad>
       <pais>
        Espa√±a
       </pais>
    </agenda>
    <resenas>
        <estrellas>
            *****
        </estrellas>
        <descripcion>
            Hotel de lujo con preciosas vistas y habitaciones premium
         </descripcion>
    </resenas>
    <habitaciones>
        <individuales>
        95
        </individuales>
        <dobles>
        76
        </dobles>
        <triples>
        34
        </triples>
        <suites>
            17
        </suites>
     </habitaciones>
</hoteles>
